const appNames = [
    "Tinder",
    "Maps",
    "Habit tracker",
    "Ebook reader",
    "Blogging platform",
    "Yelp",
    "Uber",
    "Grubhub",
    "Tic tac toe",
    "Sudoku",
    "Recipe app",
    "Weather app",
    "Crime story generator",
    "Horoscope generator",
    "Horoscope reader",
    "Calculator",
    "Note-taking app",
    "Instagram",
    "Slack",
    "List-maker",
    "Banking app",
    "Language learning app",
    "Translator",
    "Treasure hunt app",
    "YouTube",
    "Meditation app",
    "Breathing app",
    "Affirmations app",
    "Lost key locator app",
    "SMS app",
    "Plant swapping app",
    "Plant owner's guide app",
    "Tetris",
    "Storytelling app",
    "Expense trancking",
    "MTA fandom app",
    "Wikipedia",
    "Trivia app",
    "Quiz app",
    "News app",
    "Bill-splitting app",
    "Health-care scheduler",
    "Rule-setting app",
    "Project management app",
    "Not-to-do list app",
    "Reminder app",
    "Art piece generator",
    "Reporting app",
    "Journalling app",
    "Dating app",
    "Hangman game"
  ]
  
  
  
  
  
  const nouns = [
    "disillusioned corporation employee",
    "5-year-old who can read like an 8th grader",
    "extremely bored parent of three",
    "adventurous grandma",
    "person who's always unlucky",
    "person who fantasizes about winning the lottery",
    "person who likes to give advice",
    "introvert who works at a call center",
    "foodie",
    "very impatient person",
    "person who asks a lot of questions",
    "film critic who always refers to films",
    "person who likes to know everything in depth",
    "person who likes to procrastinate",
    "cheerful dentist",
    "overenthusiastic aunt",
    "overconfident uncle",
    "programmer who works on a horrible legacy code",
    "alternative history aficionado",
    "colorblind adult who loves riddles",
    "professional landscape designer",
    "person obsessed with vegetarianism",
    "air quality activist",
    "writer who writes food labels",
    "musician who has a gig soon",
    "worried trivia buff",
    "dystopia-obsessed teenager",
    "overworked mechanic",
    "person with too many pets",
    "home cook",
    "person who can't stop daydreaming",
    "person who is interested in too many things",
    "treasure hunter",
    "New York club expert",
    "New Yorker's fact checker",
    "owner of a quaint cafe in Bushwick",
    "someone who gets too jittery when drinking coffee",
    "amateur architect who won't accept a gig unless it's the next Empire State Building",
    "watercolor painter who paints only wintery landscapes",
    "lifestyle expert",
    "has-been instagram influencer",
    "skateboarder who broke their fingers",
    "retired professional swimmer with low vision",
    "someone who wakes up at 11pm and doesn't like day mode",
    "non-English native speaker",
    "person who likes to 'figure it out on their own'",
    "museum connesseur",
    "entomologist who despises other animals",
    "electrician prodigy",
    "women's history professor",
    "tenured scientist who stopped believing in science"
  ]